version: "3"

services:
  rest_api:
    container_name: rest_api
    ports:
      - "5000:5000"
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env

  web:
    container_name: web
    ports:
      - 3000:3000
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    environment:
      - NEXT_PUBLIC_ENVIRONMENT=${ENVIRONMENT}
      - NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
      - NEXT_PUBLIC_SENTRY_DISABLED=${SENTRY_DISABLED}

  # expo_app:
  #   container_name: expo_app
  #   build: ./mobile
  #   ports:
  #     - 19000:19000
  #     - 19001:19001
  #     - 19002:19002
  #   environment:
  #     - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./mobile:/usr/src/app
  #     - /mobile/usr/src/app/node_modules
