version: "3"

services:

  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:alpine
    env_file:
      - .env
    restart: always

  rest_api:
    container_name: rest_api
    depends_on: postgres
    ports:
      - "5000:5000"
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/:/usr/src/app
      - /api/usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev

  web:
    depends_on: postgres
    ports:
      - 3000:3000
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/app
      - /web/usr/src/app/node_modules
      - /web/usr/src/app/.next
    env_file:
      - .env

  # expo_app:
  #   container_name: expo_app
  #   build: ./mobile
  #   ports:
  #     - 19000:19000
  #     - 19001:19001
  #     - 19002:19002
  #   environment:
  #     - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./mobile:/usr/src/app
  #     - /mobile/usr/src/app/node_modules

  firebase-emulators:
    container_name: firebase
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
    build:
      context: .
      dockerfile: Dockerfile.firebase
    image: firebase-emulator:firebase-emulator
    volumes:
      - .:/src
    command: firebase emulators:start --project dev

  pgadmin:
    container_name: pgadmin
    ports:
      - "5050:80"
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
