version: "3"

services:
  web:
    ports:
      - 3000:3000
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/app
      - /web/usr/src/app/node_modules
      - /web/usr/src/app/.next
    env_file:
      - .env

  # expo_app:
  #   container_name: expo_app
  #   build: ./mobile
  #   ports:
  #     - 19000:19000
  #     - 19001:19001
  #     - 19002:19002
  #   environment:
  #     - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
  #     - CHOKIDAR_USEPOLLING=true
  #   volumes:
  #     - ./mobile:/usr/src/app
  #     - /mobile/usr/src/app/node_modules

  rest_api:
    container_name: rest_api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/:/usr/src/app
      - /api/usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: npm run start:dev

  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: always
